### PR TITLE
Table hack

### PR DESCRIPTION
**Pull request by nicholst**
Create TabDat structure expected by spm_list, allowing access to all peak/cluster results, even if there are too many for the SnPM results page.  The TabDat structure is (inelegantly) saved to a mat file.  

Improvement that is needed is allowing this table to be printed via a context menu.

### CODE REVIEW

**Comment by nicholst** [comment]
New commits to give same functionality as SPM: Context menu to access table of results via text, matlab structure or CSV file.  Also copied (from spm_list) functionality to export to Excel on a PC but haven't tested this.  @cmaumet - This is great! Now it works just like SPM!

**Comment by nicholst** [comment]
@cmaumet If you want to develop tests on the TabDat table structure, here are some hints (and, aside from testing this very bit of code, it might be a useful way to test the actual content of the SnPM results table).

This of course assumes you've already run SnPM Inference and there is a current result displayed.

```matlab
% Find the axis from which the context-menu arises
obj=findobj(spm_figure('FindWin','Graphics'),'Tag','TabDat'); 
% Get TabDat structure
TabDat=get(obj,'UserData');
% Write CSV table
snpm_list('csvlist',TabDat,'/tmp/file.csv');
% Text rendering of TabDat
diary /tmp/file.txt
spm_list('txtlist',TabDat);
diary off
```

**Comment by nicholst** [comment]
Based on the most recent commits, Yangwen Xu reported:

> All the functions are right now, including "Print text table", "Extract table data structure", "Export to CSV File", and "Export to excel". Now it's very convenient to export the results.

This is good to hear, but especially about Excel as I don't have a PC to check it.

**Comment by cmaumet** [comment]
This PR was not marked as merged as part of #50 because of commit 19cf355. After doublechecking it turns out that 19cf355 had been replaced by https://github.com/SnPM-toolbox/SnPM-devel/pull/50/commits/5b463f69feebfb0ff74edf48e8855dd88dc34578 in #50 so all the changes in this PR have actually been included in SnPM 13.1.07. I will therefore close this (virtually already merged) PR now.

**Pull request closed without merging**
