### PR TITLE
Version Number checking

### PR DESCRIPTION
**Pull request by TomMaullin**
#### What does this PR do?

Hi @nicholst , @cmaumet ,

As requested I have quickly added the update @nicholst suggested in PR #75 to add a version checking function to SnPM. Please let me know if you have any feedback/suggestions. I wasn't sure whether to leave the link the user is referred to as the github link or NISOx.org link so have currently left this as the github link but can change if you would like.

#### Link to relevant issues

#75 

#### PR submission checklist
 - ~~[ ] Run the tests (cf. [instructions](https://github.com/SnPM-toolbox/SnPM-devel#non-regression-testing)~~
 - ~~[ ] Copy/paste the test report in a comment below~~
 - ~~[ ] All tests in the test suite pass~~

Tests were not run as the functionality which the tests check cannot be affected by this update.

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @TomMaullin! This looks good to me but is there a way to download the release and update the local SnPM when a newer version is found? This would be similar to `spm_update update`?

Note: Can you fill in the "PR submission checklist"?

**Comment by TomMaullin** [comment]
Hi @cmaumet , 

I am a little confused by the behaviour of `spm_update('Update')`. If I run this, does the entire SPM directory just get replaced? I was just wondering if this is the correct behavior as the user could have files inside the SPM directory which they wish to keep.

**Comment by nicholst** [comment]
Add a newline

**Comment by cmaumet** [comment]
Discussed with @nicholst and @TomMaullin, we decided against having the `spm_update('update')` feature.

**Comment by nicholst** [comment]
No need to have full SPM-like download capability.

**Pull request merged**
